name: Automate labeled issues
on:
  issues:
    types: [labeled]
jobs:
  Move_Blocked_Issue_On_Working_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.vsphere_github_actions }}"
        project-url: "https://github.com/terraform-providers/terraform-provider-vsphere/projects/9"
        column-name: "Blocked"
        label-name: "waiting-response"
  Move_Triaged_Issue_On_Triage_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.vsphere_github_actions }}"
        project-url: "https://github.com/terraform-providers/terraform-provider-vsphere/projects/8"
        column-name: "Requires Investigation"
        label-name: "requires investigation"
  Move_Crash_Issue_On_Working_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.vsphere_github_actions }}"
        project-url: "https://github.com/terraform-providers/terraform-provider-vsphere/projects/9"
        column-name: "Roadmap"
        label-name: "crash"
